### ISSUE TITLE
Wrong parameter declaration for measurementContainerElement  in TS

### ISSUE THREAD

**Issue by my3188** [gnir-work/react-window-dynamic-list#24]
node_modules\react-window-dynamic-list\types\index.d.ts 
measurementContainerElement?: (style: CSSProperties, children: ReactChildren) => ReactNode;

should be :
measurementContainerElement?: ({ style, children }: {style: CSSProperties, children: ReactChildren}) => ReactNode;

**Comment by gnir-work** [comment]
Hey, sorry for the late update. 
I will take a look at it tomorow / the next week :)

**Comment by gnir-work** [comment]
Fixed in [the following PR](https://github.com/gnir-work/react-window-dynamic-list/pull/26) :)
You can update to latest version `npm i react-window-dynamic-list@2.4.0` in order to recieve the changes.
I am closing the issue for now, in case something else pops up you are more than welcomed to reopen it.
