### ISSUE TITLE
Calling resetAfterIndex on list instance does not affect layout

### ISSUE THREAD

**Issue by SpadarShut** [gnir-work/react-window-dynamic-list#25]
The library still uses cached values after calling `resetAfterIndex` method of the rect-window list.

I can make a PR if you tell what's the proper way to fix it.

**Comment by gnir-work** [comment]
Hey, I will probably look into it tomorow.
If you have the time to send a  Codesandbox it will be much appreciated :)

**Comment by gnir-work** [comment]
Fixed in [the following PR](https://github.com/gnir-work/react-window-dynamic-list/pull/27) :)
You can update to latest version `npm i react-window-dynamic-list@2.4.0` in order to recieve the changes.

**Comment by SpadarShut** [comment]
Great, thank you! 

I found an issue, though. During `npm install` I get an error that this package has react 16 in peer dependencies, which conflicts with my projects's dependency on v17. Can you please add 17 (and maybe 18?) too?

**Comment by gnir-work** [comment]
Hey!
Thanks for the feedback, Fixed in version 2.4.1 :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
